### PR TITLE
Added xlims to distributions

### PR DESCRIPTION
**Pull request by mustafaascha**
The range of the data is important, but maybe not at the expense of other information about the distribution (particularly for the "Histogram of ROI").

### CODE REVIEW

**Comment by mustafaascha** [comment]
Alternatively, maybe change the number of bins?

**Comment by ismayc** [comment]
While I certainly thought about this when making the histograms, I tend to not like to cut off data being plotted manually using `xlims` by default.  Some discussion could certainly be added after the Histogram of ROI leading into the Histogram of Logarithm of ROI as to why that choice was made.  If you'd like to make that addition, we'd be happy to grant the pull request.

**Comment by ismayc** [comment]
Changing the number of bins is a good suggestion too.  I kept them at 20 since that seemed to cover all of the plots OK.

**Comment by mustafaascha** [comment]
Cool! Thanks for adding it! Happy to contribute.

**Comment by ismayc** [comment]
Thanks for the contribution!  I've added a link to your GitHub page in the bechdel Rmd and a note that this was your suggestion.

**Pull request merged**
