### PR TITLE
fivethirtyeight needn't suggest itself

### PR DESCRIPTION
**Pull request by davidsgrogan**
Though I don't really know the convention here.

### CODE REVIEW

**Comment by rudeboybert** [comment]
Hmm, I'm not sure if that inclusion was by design or not. I will test this later once I have more time. Thanks for alerting!

**Comment by rudeboybert** [comment]
@ismayc @jchunn Was there a reason this package requires itself?

**Comment by ismayc** [comment]
For some reason Travis wouldn’t go through without it. Hopefully it works now.

**Comment by rudeboybert** [comment]
Huh, Travis CI checks pass and after a local build no issues. Approved.

BTW @ismayc, @davidsgrogan is the one who first explained to me what GitHub was back in 2013. And while counterfactually speaking if it weren't him, it would've eventually been someone else, I'm still thankful!

**Comment by ismayc** [comment]
Awesome story! Thanks much, @davidsgrogan!

**Pull request merged**
