### PR TITLE
Revert "fivethirtyeight needn't suggest itself"

### PR DESCRIPTION
**Pull request by rudeboybert**
Reverts rudeboybert/fivethirtyeight#32

### CODE REVIEW

**Comment by rudeboybert** [comment]
@davidsgrogan it seems that `fivethirtyeight` NEED suggest itself as per @ismayc suspicion. We have to revert this.

**Comment by ismayc** [comment]
@rudeboybert What was the error produced? We might want to investigate further since it is a little strange.

**Comment by rudeboybert** [comment]
Yeah, it turns out the culprit might not be @davidsgrogan's PR. Can you see this [link](https://travis-ci.org/rudeboybert/fivethirtyeight/jobs/432886646)? If not, below is a screenshot. It has something to do with `pkgdown`. I'm currently rebuilding site locally

error

**Comment by ismayc** [comment]
I think there's something with `pkgdown` and that's why we had to include `fivethirtyeight` again. I did a Google search of the "is non-empty and not built by pkgdown" error and most things seem to lead to it being really tricky to get `pkgdown` working with travis. It appears we've hacked it here, but I'm not sure why `pkgdown` works for other packages without the circular package dependency. Maybe try to do the same for another data package and see if that's the problem?

**Comment by rudeboybert** [comment]
I tried for `moderndive/moderndive` and had no problems.

**Comment by ismayc** [comment]
I wonder if it has to do with the vignettes? That’s the only major difference I can think of.

**Comment by davidsgrogan** [comment]
I genuinely apologize for opening this can of worms... I was just messing around. The circular dependency (if you can even call it that as it's not in the "required" section, just the recommends section IIRC) probably isn't an actual problem to the extent that it isn't masking something more serious.

**Comment by rudeboybert** [comment]
A little context: we're having issues with travis-ci automating deployment of another website. So this is all part of a larger debugging operation. So no worries!

**Comment by rudeboybert** [comment]
@davidsgrogan is correct: PACKAGES NEEDN'T REQUIRE THEMSELVES! LET THERE BE REJOICING.

If you care, the issue was the travis-ci automated deployment of the pkgdown website was being thrown off by the presence of a `docs/` folder in the master branch of the repo. A simple adding of `docs/*` to `.gitignore` solved the pkgdown issue, allowing for all builds to pass. Found the suggestion in this excellent blogpost [Continuous deployment of package documentation with pkgdown and Travis CI](https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis)

**Pull request merged**
